name: Code Quality

on:
  workflow_call:
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod

      - name: Run Go tests
        working-directory: ./backend
        run: go test ./...

      - name: Run Go vet
        working-directory: ./backend
        run: go vet ./...
